# Generated by Django 5.2.4 on 2025-07-05 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('category_slug', models.SlugField(editable=False, unique=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('category_description', models.TextField(default='no description')),
                ('category_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='shop.categories')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product_description', models.CharField(default='no deascription', max_length=255)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product_stock', models.IntegerField(default=0)),
                ('product_uploadDate', models.DateField(auto_now_add=True)),
                ('product_reviews', models.IntegerField(default=0)),
                ('product_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('product_brand', models.CharField(default='no brand', max_length=50)),
                ('product_details', models.TextField(default='no details')),
                ('product_orders', models.IntegerField(default=0)),
                ('product_category', models.ManyToManyField(blank=True, to='shop.categories')),
            ],
        ),
    ]
