# Generated by Django 5.2.4 on 2025-07-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
