# Generated by Django 5.2.4 on 2025-07-03 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_product_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_brand',
            field=models.CharField(default='no brand', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='product_details',
            field=models.TextField(default='no details'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
