# Generated by Django 5.2.4 on 2025-07-03 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_product_product_brand_product_product_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
                ('category_slug', models.SlugField(unique=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='category_images/')),
                ('category_description', models.TextField(default='no description')),
                ('category_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.categories')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ManyToManyField(blank=True, to='shop.categories'),
        ),
    ]
